# Generated by Django 5.0.6 on 2024-07-12 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('car_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car')),
            ],
        ),
    ]
