# Generated by Django 5.0.6 on 2024-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_addmusicianmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmusicianmodel',
            name='instrument_type',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('piano', 'Piano'), ('drums', 'Drums'), ('violin', 'Violin'), ('flute', 'Flute')], max_length=50),
        ),
    ]
