# Generated by Django 5.0.6 on 2024-06-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('posts', '0003_alter_post_author_alter_post_post_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
