# Generated by Django 5.0.6 on 2024-06-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default=None, upload_to='posts/media/uploads/'),
        ),
    ]
