# Generated by Django 5.0.6 on 2024-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelform',
            name='email',
            field=models.EmailField(default='Null', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='modelform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
