# Generated by Django 5.0.6 on 2024-06-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_modelform_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelform',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='./Photos/'),
        ),
    ]
