# Generated by Django 5.0.6 on 2024-06-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0003_alter_addmusicianmodel_instrument_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField(auto_now=True)),
                ('rating', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=50)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.addmusicianmodel')),
            ],
        ),
    ]
