# Generated by Django 5.0.6 on 2024-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addalbummodel',
            name='id',
        ),
        migrations.AddField(
            model_name='addalbummodel',
            name='aid',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
