# Generated by Django 5.0.6 on 2024-06-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_modelform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelform',
            name='profile_pic',
            field=models.FileField(default=None, upload_to=None),
        ),
    ]
